full-stack/Price-of-Item-Web/src/app.py
from flask import Flask, render_template
from src.common.database import Database

app = Flask(__name__)
app.config.from_object('config')
app.secret_key = "shravan"


@app.before_first_request
def init_db():
    Database.initialize()


@app.route('/')
def home():
    return render_template('home.j2')


from src.models.users.views import user_blueprint
app.register_blueprint(user_blueprint, url_prefix='/users')

from src.models.stores.views import store_blueprint
app.register_blueprint(store_blueprint, url_prefix='/stores')

from src.models.alerts.views import alert_blueprint
app.register_blueprint(alert_blueprint, url_prefix='/alerts')

full-stack/Price-of-Item-Web/src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as user_decorators

alert_blueprint = Blueprint("alerts", __name__)


@alert_blueprint.route('/new', methods=['GET','POST'])
@user_decorators.requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['name']
        url = request.form['url']
        price_limit = float(request.form['price_limit'])

        item = Item(name=name, url=url)
        item.save_to_db()

        alert = Alert(user_email=session['email'], price_limit=price_limit, item_id=item._id)
        alert.load_item_price()  # This already saves to the database

    return render_template('alerts/create_alert.j2')


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@user_decorators.requires_login
def edit_alert(alert_id):
    alert = Alert.find_by_id(alert_id)
    if request.method == 'POST':
        price_limit = float(request.form['price_limit'])

        alert.price_limit = price_limit
        alert.save_to_db()

        return redirect(url_for('users.user_alerts'))

    return render_template('alerts/edit_alert.j2', alert=alert)


@alert_blueprint.route('/deactivate/<string:alert_id>')
@user_decorators.requires_login
def deactivate_alert(alert_id):
    Alert.find_by_id(alert_id).deactivate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/activate/<string:alert_id>')
@user_decorators.requires_login
def activate_alert(alert_id):
    Alert.find_by_id(alert_id).activate()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/delete/<string:alert_id>')
@user_decorators.requires_login
def delete_alert(alert_id):
    Alert.find_by_id(alert_id).delete()
    return redirect(url_for('users.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@user_decorators.requires_login
def get_alert_page(alert_id):
    alert = Alert.find_by_id(alert_id)
    return render_template('alerts/alert.j2', alert=alert)


@alert_blueprint.route('/check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.find_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))

full-stack/Price-of-Item-Web/src/models/items/views.py
from flask import Blueprint


item_blueprint = Blueprint("items", __name__)


@item_blueprint.route("/item/<string:name")
def item_page(name):
    pass

full-stack/Price-of-Item-Web/src/models/stores/views.py
from flask import Blueprint, render_template, request, json, url_for, redirect

from src.models.stores.store import Store
import src.models.users.decorators as user_decorators

store_blueprint = Blueprint("stores", __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_index.j2', stores=stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.j2', store=Store.get_by_id(store_id))


@store_blueprint.route('/new', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        Store(name=name, url_prefix=url_prefix, tag_name=tag_name, query=query).save_to_db()

        return redirect(url_for('.index'))

    return render_template('stores/create_store.j2')


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@user_decorators.requires_admin_permissions
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag_name = request.form['tag_name']
        query = json.loads(request.form['query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag_name
        store.query = query

        store.save_to_db()

        return redirect(url_for('.index'))

    return render_template('stores/edit_store.j2', store=store)


@store_blueprint.route('/delete/<string:store_id>')
@user_decorators.requires_admin_permissions
def delete_store(store_id):
    Store.get_by_id(store_id).delete()
    return redirect(url_for('.index'))

full-stack/Price-of-Item-Web/src/models/users/views.py
from flask import Blueprint, request, session, url_for, render_template, redirect

from src.models.users.user import User
import src.models.users.errors as UserError
import src.models.users.decorators as user_decorators

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_valid_login(email, password):
                session["email"] = email
                return redirect(url_for(".user_alerts"))
        except UserError.UserError as e:
            return e.message

    return render_template("users/login.j2")


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for('.user_alerts'))
        except UserError.UserError as e:
            return e.message

    return render_template('users/register.j2')


@user_blueprint.route('/alerts')
@user_decorators.requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template('/users/alerts.j2', alerts= alerts)


@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alert(user_id):
    pass

full-stack/Price-of-Item-Web/src/templates/alerts/alert.j2
{% extends "base.j2" %}
{% block content %}
    <div class="page-header">
        <h1>Alert <small>for '{{ alert.item.name }}'</small></h1>
    </div>
    <p>Last price found <strong>{{ alert.item.price }}</strong></p>
    <p>Last checked on <strong>{{ alert.last_checked.strftime('%d-%m-%y at %H:%M') }}</strong></p>
    <div class="card">
        <div class="card-body">
            <a class="btn btn-primary" href="{{ alert.item_url  }}" role="button">Visit Site</a>
            <a class="btn btn-warning" href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}" role="button">Edit Alert</a>
            {% if alert.active %}
                <a class="btn btn-danger" href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}" role="button">Deactivate Alert</a>
            {% else %}
                <a class="btn btn-success" href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}" role="button">Activate Alert</a>
                 <a class="btn btn-danger" href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}" role="button">Delete Alert</a>
            {% endif %}
            <a class="btn btn-warning" href="{{ url_for('alerts.check_alert_price', alert_id=alert._id) }}" role="button">Check Price</a>
        </div>
    </div>
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/alerts/create_alert.j2
{% extends "base.j2" %}
{% block content %}
    <div class="page-header">
        <h1>Create a New Alert</h1>
    </div>
    <div class="form-size">
        <form action="{{ url_for('alerts.create_alert') }}" method="post">
            <form>
              <div class="form-group">
                <label for="name">Alert/Item Title</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
              </div>
              <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="URL http(s)://....">
              </div>
              <div class="form-group">
                <label for="price_limit">Price Limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="$20.0" aria-describedby="priceLimitHelp">
                <small id="priceLimitHelp" class="form-text text-muted">We'll send you an emmail when the price reaches or goes under the Price Limit.</small>
              </div>
              <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </form>
    </div>
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/alerts/edit_alert.j2
{% extends "base.j2" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Alert</h1>
    </div>
    <div class="form-size">
        <form method="post">
            <form>
              <div class="form-group">
                <label for="name">Alert/Item Title</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name" disabled value="{{ alert.name }}">
              </div>
              <div class="form-group">
                <label for="url">URL</label>
                <input type="text" class="form-control" id="url" name="url" placeholder="URL http(s)://...." value="{{ alert.url }}" disabled>
              </div>
              <div class="form-group">
                <label for="price_limit">Price Limit</label>
                <input type="text" class="form-control" id="price_limit" name="price_limit" placeholder="$20.0" value="{{ alert.price_limit }}" aria-describedby="priceLimitHelp">
                <small id="priceLimitHelp" class="form-text text-muted">We'll send you an emmail when the price reaches or goes under the Price Limit.</small>
              </div>
              <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </form>
    </div>
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/base.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing Alert Service</title>

    {% include 'html_dependencies.j2' %}

</head>
<body>
<div id="app" class="container">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F5F5F5;">
        <a class="navbar-brand" href="/">Pricing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarNavDropdown" class="navbar-collapse collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <i class="fas fa-home"></i><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('stores.index') }}">Stores</a>
                </li>
            </ul>
            {% if session['email'] %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.user_alerts') }}">Your Alerts <i class="fas fa-bell"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.logout_user') }}">Logout <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                </ul>
            {% else %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.login_user') }}">Login <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.register_user') }}">Register <i class="fas fa-user-plus"></i></a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </nav>
</div>

<div class = "content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

full-stack/Price-of-Item-Web/src/templates/home.j2
{% extends "base.j2" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Pricing Service!</h1>
        <p class="lead">We scan online websites to alert you of price drops in items that interest you.</p>
        <hr class="my-4">
        <p>Come and Sign Up and add the URL of the item you wish to track.</p>
        <a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign Up</a>
    </div>
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/html_dependencies.j2
<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link href="{{ url_for('static', filename = 'css/style.css') }}" rel="stylesheet">
<link href="/static/fontawesome/fontawesome-all.css" rel="stylesheet">

full-stack/Price-of-Item-Web/src/templates/stores/create_store.j2
{% extends "base.j2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Store </h1>
    </div>
    <div class="form-size">
        <form method="post">
            <form>
              <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
              </div>
              <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http(s)://...." aria-describedby="urlPrefixHelp">
                <small id="urlPrefixHelp" class="form-text text-muted">What characters dp URLs of all items in this store start with.</small>
              </div>
              <div class="form-group">
                <label for="tag_name">Store URL Prefix</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="span" aria-describedby="storeTagNameHelp">
                <small id="storeTagNameHelp" class="form-text text-muted">What is the HTML tag name of the item that contains the item price? (usually <code>span </code>)</small>
              </div>
              <div class="form-group">
                <label for="query">Store URL Prefix</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value='{"id": "price-now"}' aria-describedby="queryHelp">
                <small id="queryHelp" class="form-text text-muted">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation maarks!</small>
              </div>
              <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </form>
    </div>
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/stores/edit_store.j2
{% extends "base.j2" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Store </h1>
    </div>
    <div class="form-size">
        <form method="post">
            <form>
              <div class="form-group">
                <label for="name">Store Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ store.name }}">
              </div>
              <div class="form-group">
                <label for="url_prefix">Store URL Prefix</label>
                <input type="text" class="form-control" id="url_prefix" name="url_prefix" placeholder="http(s)://...." value="{{ store.url_prefix }}" aria-describedby="urlPrefixHelp">
                <small id="urlPrefixHelp" class="form-text text-muted">What characters dp URLs of all items in this store start with.</small>
              </div>
              <div class="form-group">
                <label for="tag_name">Store URL Prefix</label>
                <input type="text" class="form-control" id="tag_name" name="tag_name" placeholder="span" value="{{ store.tag_name }}" aria-describedby="storeTagNameHelp">
                <small id="storeTagNameHelp" class="form-text text-muted">What is the HTML tag name of the item that contains the item price? (usually <code>span </code>)</small>
              </div>
              <div class="form-group">
                <label for="query">Store URL Prefix</label>
                <input type="text" class="form-control" id="query" name="query" placeholder='{"id": "price-now"}' value='{{ store.query | tojson }}' aria-describedby="queryHelp">
                <small id="queryHelp" class="form-text text-muted">What JSON query would we have to do to find the specific tag with the price? Remember to use double quotation maarks!</small>
              </div>
              <button type="submit" class="btn btn-success">Edit Store</button>
            </form>
        </form>
    </div>
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/stores/store.j2
{% extends "base.j2" %}
{% block content %}
    <div class="page-header">
        <h1>Store <small>{{ store.name }}</small></h1>
    </div>
    <p>All URL's for this store must begin with <strong>{{ store.url_prefix }}</strong></p>
    {% if session['email'] in config.ADMINS %}
    <div class="card">
        <div class="card-body">
            <a class="btn btn-warning" href="{{ url_for('stores.edit_store', store_id=store._id)  }}" role="button">Edit Store</a>
            <a class="btn btn-danger" href="{{ url_for('stores.delete_store', store_id=store._id) }}" role="button">Delete Store</a>
        </div>
    </div>
    {% endif %}
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/stores/store_index.j2
{% extends "base.j2" %}
{% block content %}
    <div class="page-header">
        <h1>Stores <small>List of supported stores</small></h1>
    </div>
    <div class="list-group">
        {% for store in stores %}
            <a href="{{ url_for('stores.store_page', store_id=store._id) }}" class="list-group-item">
                <h4 class="list-group-item-heading">{{ store.name }}</h4>
                <p class="List-group-item-text">All URL's in this store should start with <strong>{{ store.url_prefix }}</strong></p>
            </a>
        {% endfor %}
     </div>
    {% if session['email'] in config.ADMINS %}
     <a class="btn btn-success" href="{{ url_for('stores.create_store') }}"><i class="fas fa-plus-circle"></i> Create New Store</a>
    {% endif %}
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/users/alerts.j2
{% extends "base.j2" %}
{% block content %}
    <div class="page-header">
        <h1>Alerts <small>Showing already existing alerts</small></h1>
    </div>

    <div class="list-group">
        {% for alert in alerts %}
            <a href="{{ url_for('alerts.get_alert_page', alert_id = alert._id) }}" class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}">
                <h4 class="list-group-item-heading">{{ '<i class="fas fa-minus-circle"></i>' if not alert.active else '<i class="far fa-check-circle"></i>' }} Alert for {{ alert.item.name }}</h4>
                <p class="List-group-item-text">Last price found <strong>{{ alert.item.price }}</strong><br/>
                    Last Checked on <strong>{{ alert.last_checked.strftime("%d-%m-%y at %H:%M") }}</strong></p>
            </a>
        {% endfor %}
     </div>
     <a class="btn btn-success" href="{{ url_for('alerts.create_alert') }}"><i class="fas fa-plus-circle"></i> Create New Alert</a>
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/users/login.j2
{% extends "base.j2" %}
{% block content %}
<div class="form-size">
    <form action="{{ url_for('users.login_user') }}" method="post">
        <form>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </form>
</div>
{% endblock %}

full-stack/Price-of-Item-Web/src/templates/users/register.j2
{% extends "base.j2" %}
{% block content %}
<div class="form-size">
    <form action="{{ url_for('users.register_user') }}" method="post">
        <form>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </form>
</div>
{% endblock %}